@ cdecl nvmlComputeInstanceDestroy(ptr)
@ cdecl nvmlComputeInstanceGetInfo(ptr ptr)
@ cdecl nvmlComputeInstanceGetInfo_v2(ptr ptr)
@ cdecl nvmlDeviceClearAccountingPids(ptr)
@ cdecl nvmlDeviceClearCpuAffinity(ptr)
@ cdecl nvmlDeviceClearEccErrorCounts(ptr ptr)
@ cdecl nvmlDeviceCreateGpuInstance(ptr long ptr)
@ cdecl nvmlDeviceCreateGpuInstanceWithPlacement(ptr long ptr ptr)
@ cdecl nvmlDeviceDiscoverGpus(ptr)
@ cdecl nvmlDeviceFreezeNvLinkUtilizationCounter(ptr long long long)
@ cdecl nvmlDeviceGetAPIRestriction(ptr long ptr)
@ cdecl nvmlDeviceGetAccountingBufferSize(ptr ptr)
@ cdecl nvmlDeviceGetAccountingMode(ptr ptr)
@ cdecl nvmlDeviceGetAccountingPids(ptr ptr ptr)
@ cdecl nvmlDeviceGetAccountingStats(ptr long ptr)
@ cdecl nvmlDeviceGetActiveVgpus(ptr ptr ptr)
@ cdecl nvmlDeviceGetApplicationsClock(ptr long ptr)
@ cdecl nvmlDeviceGetArchitecture(ptr ptr)
@ cdecl nvmlDeviceGetAttributes(ptr ptr)
@ cdecl nvmlDeviceGetAttributes_v2(ptr ptr)
@ cdecl nvmlDeviceGetAutoBoostedClocksEnabled(ptr ptr ptr)
@ cdecl nvmlDeviceGetBAR1MemoryInfo(ptr ptr)
@ cdecl nvmlDeviceGetBoardId(ptr ptr)
@ cdecl nvmlDeviceGetBoardPartNumber(ptr ptr long)
@ cdecl nvmlDeviceGetBrand(ptr ptr)
@ cdecl nvmlDeviceGetBridgeChipInfo(ptr ptr)
@ cdecl nvmlDeviceGetClock(ptr long long ptr)
@ cdecl nvmlDeviceGetClockInfo(ptr long ptr)
@ cdecl nvmlDeviceGetComputeInstanceId(ptr ptr)
@ cdecl nvmlDeviceGetComputeMode(ptr ptr)
@ cdecl nvmlDeviceGetComputeRunningProcesses(ptr ptr ptr)
@ cdecl nvmlDeviceGetComputeRunningProcesses_v2(ptr ptr ptr)
@ cdecl nvmlDeviceGetCount(ptr)
@ cdecl nvmlDeviceGetCount_v2(ptr)
@ cdecl nvmlDeviceGetCpuAffinity(ptr long ptr)
@ cdecl nvmlDeviceGetCpuAffinityWithinScope(ptr long ptr long)
@ cdecl nvmlDeviceGetCreatableVgpus(ptr ptr ptr)
@ cdecl nvmlDeviceGetCudaComputeCapability(ptr ptr ptr)
@ cdecl nvmlDeviceGetCurrPcieLinkGeneration(ptr ptr)
@ cdecl nvmlDeviceGetCurrPcieLinkWidth(ptr ptr)
@ cdecl nvmlDeviceGetCurrentClocksThrottleReasons(ptr ptr)
@ cdecl nvmlDeviceGetDecoderUtilization(ptr ptr ptr)
@ cdecl nvmlDeviceGetDefaultApplicationsClock(ptr long ptr)
@ cdecl nvmlDeviceGetDetailedEccErrors(ptr long long ptr)
@ cdecl nvmlDeviceGetDeviceHandleFromMigDeviceHandle(ptr ptr)
@ cdecl nvmlDeviceGetDisplayActive(ptr ptr)
@ cdecl nvmlDeviceGetDisplayMode(ptr ptr)
@ cdecl nvmlDeviceGetDriverModel(ptr ptr ptr)
@ cdecl nvmlDeviceGetEccMode(ptr ptr ptr)
@ cdecl nvmlDeviceGetEncoderCapacity(ptr long ptr)
@ cdecl nvmlDeviceGetEncoderSessions(ptr ptr ptr)
@ cdecl nvmlDeviceGetEncoderStats(ptr ptr ptr ptr)
@ cdecl nvmlDeviceGetEncoderUtilization(ptr ptr ptr)
@ cdecl nvmlDeviceGetEnforcedPowerLimit(ptr ptr)
@ cdecl nvmlDeviceGetFBCSessions(ptr ptr ptr)
@ cdecl nvmlDeviceGetFBCStats(ptr ptr)
@ cdecl nvmlDeviceGetFanSpeed(ptr ptr)
@ cdecl nvmlDeviceGetFanSpeed_v2(ptr long ptr)
@ cdecl nvmlDeviceGetFieldValues(ptr long ptr)
@ cdecl nvmlDeviceGetGpuInstanceById(ptr long ptr)
@ cdecl nvmlDeviceGetGpuInstanceId(ptr ptr)
@ cdecl nvmlDeviceGetGpuInstancePossiblePlacements(ptr long ptr ptr)
@ cdecl nvmlDeviceGetGpuInstanceProfileInfo(ptr long ptr)
@ cdecl nvmlDeviceGetGpuInstanceRemainingCapacity(ptr long ptr)
@ cdecl nvmlDeviceGetGpuInstances(ptr long ptr ptr)
@ cdecl nvmlDeviceGetGpuOperationMode(ptr ptr ptr)
@ cdecl nvmlDeviceGetGraphicsRunningProcesses(ptr ptr ptr)
@ cdecl nvmlDeviceGetGraphicsRunningProcesses_v2(ptr ptr ptr)
@ cdecl nvmlDeviceGetGridLicensableFeatures(ptr ptr)
@ cdecl nvmlDeviceGetGridLicensableFeatures_v2(ptr ptr)
@ cdecl nvmlDeviceGetGridLicensableFeatures_v3(ptr ptr)
@ cdecl nvmlDeviceGetHandleByIndex(long ptr)
@ cdecl nvmlDeviceGetHandleByIndex_v2(long ptr)
@ cdecl nvmlDeviceGetHandleByPciBusId(str ptr)
@ cdecl nvmlDeviceGetHandleByPciBusId_v2(str ptr)
@ cdecl nvmlDeviceGetHandleBySerial(str ptr)
@ cdecl nvmlDeviceGetHandleByUUID(str ptr)
@ cdecl nvmlDeviceGetHostVgpuMode(ptr ptr)
@ cdecl nvmlDeviceGetIndex(ptr ptr)
@ cdecl nvmlDeviceGetInforomConfigurationChecksum(ptr ptr)
@ cdecl nvmlDeviceGetInforomImageVersion(ptr ptr long)
@ cdecl nvmlDeviceGetInforomVersion(ptr long ptr long)
@ cdecl nvmlDeviceGetMPSComputeRunningProcesses(ptr ptr ptr)
@ cdecl nvmlDeviceGetMaxClockInfo(ptr long ptr)
@ cdecl nvmlDeviceGetMaxCustomerBoostClock(ptr long ptr)
@ cdecl nvmlDeviceGetMaxMigDeviceCount(ptr ptr)
@ cdecl nvmlDeviceGetMaxPcieLinkGeneration(ptr ptr)
@ cdecl nvmlDeviceGetMaxPcieLinkWidth(ptr ptr)
@ cdecl nvmlDeviceGetMemoryAffinity(ptr long ptr long)
@ cdecl nvmlDeviceGetMemoryErrorCounter(ptr long long long ptr)
@ cdecl nvmlDeviceGetMemoryInfo(ptr ptr)
@ cdecl nvmlDeviceGetMigDeviceHandleByIndex(ptr long ptr)
@ cdecl nvmlDeviceGetMigMode(ptr ptr ptr)
@ cdecl nvmlDeviceGetMinorNumber(ptr ptr)
@ cdecl nvmlDeviceGetMultiGpuBoard(ptr ptr)
@ cdecl nvmlDeviceGetName(ptr ptr long)
@ cdecl nvmlDeviceGetNvLinkCapability(ptr long long ptr)
@ cdecl nvmlDeviceGetNvLinkErrorCounter(ptr long long ptr)
@ cdecl nvmlDeviceGetNvLinkRemotePciInfo(ptr long ptr)
@ cdecl nvmlDeviceGetNvLinkRemotePciInfo_v2(ptr long ptr)
@ cdecl nvmlDeviceGetNvLinkState(ptr long ptr)
@ cdecl nvmlDeviceGetNvLinkUtilizationControl(ptr long long ptr)
@ cdecl nvmlDeviceGetNvLinkUtilizationCounter(ptr long long ptr ptr)
@ cdecl nvmlDeviceGetNvLinkVersion(ptr long ptr)
@ cdecl nvmlDeviceGetP2PStatus(ptr ptr long ptr)
@ cdecl nvmlDeviceGetPciInfo(ptr ptr)
@ cdecl nvmlDeviceGetPciInfo_v2(ptr ptr)
@ cdecl nvmlDeviceGetPciInfo_v3(ptr ptr)
@ cdecl nvmlDeviceGetPcieReplayCounter(ptr ptr)
@ cdecl nvmlDeviceGetPcieThroughput(ptr long ptr)
@ cdecl nvmlDeviceGetPerformanceState(ptr ptr)
@ cdecl nvmlDeviceGetPersistenceMode(ptr ptr)
@ cdecl nvmlDeviceGetPgpuMetadataString(ptr ptr ptr)
@ cdecl nvmlDeviceGetPowerManagementDefaultLimit(ptr ptr)
@ cdecl nvmlDeviceGetPowerManagementLimit(ptr ptr)
@ cdecl nvmlDeviceGetPowerManagementLimitConstraints(ptr ptr ptr)
@ cdecl nvmlDeviceGetPowerManagementMode(ptr ptr)
@ cdecl nvmlDeviceGetPowerState(ptr ptr)
@ cdecl nvmlDeviceGetPowerUsage(ptr ptr)
@ cdecl nvmlDeviceGetProcessUtilization(ptr ptr ptr int64)
@ cdecl nvmlDeviceGetRemappedRows(ptr ptr ptr ptr ptr)
@ cdecl nvmlDeviceGetRetiredPages(ptr long ptr ptr)
@ cdecl nvmlDeviceGetRetiredPagesPendingStatus(ptr ptr)
@ cdecl nvmlDeviceGetRetiredPages_v2(ptr long ptr ptr ptr)
@ cdecl nvmlDeviceGetRowRemapperHistogram(ptr ptr)
@ cdecl nvmlDeviceGetSamples(ptr long int64 ptr ptr ptr)
@ cdecl nvmlDeviceGetSerial(ptr ptr long)
@ cdecl nvmlDeviceGetSupportedClocksThrottleReasons(ptr ptr)
@ cdecl nvmlDeviceGetSupportedEventTypes(ptr ptr)
@ cdecl nvmlDeviceGetSupportedGraphicsClocks(ptr long ptr ptr)
@ cdecl nvmlDeviceGetSupportedMemoryClocks(ptr ptr ptr)
@ cdecl nvmlDeviceGetSupportedVgpus(ptr ptr ptr)
@ cdecl nvmlDeviceGetTemperature(ptr long ptr)
@ cdecl nvmlDeviceGetTemperatureThreshold(ptr long ptr)
@ cdecl nvmlDeviceGetTopologyCommonAncestor(ptr ptr ptr)
@ cdecl nvmlDeviceGetTopologyNearestGpus(ptr long ptr ptr)
@ cdecl nvmlDeviceGetTotalEccErrors(ptr long long ptr)
@ cdecl nvmlDeviceGetTotalEnergyConsumption(ptr ptr)
@ cdecl nvmlDeviceGetUUID(ptr ptr long)
@ cdecl nvmlDeviceGetUtilizationRates(ptr ptr)
@ cdecl nvmlDeviceGetVbiosVersion(ptr ptr long)
@ cdecl nvmlDeviceGetVgpuMetadata(ptr ptr ptr)
@ cdecl nvmlDeviceGetVgpuProcessUtilization(ptr int64 ptr ptr)
@ cdecl nvmlDeviceGetVgpuUtilization(ptr int64 ptr ptr ptr)
@ cdecl nvmlDeviceGetViolationStatus(ptr long ptr)
@ cdecl nvmlDeviceGetVirtualizationMode(ptr ptr)
@ cdecl nvmlDeviceIsMigDeviceHandle(ptr ptr)
@ cdecl nvmlDeviceModifyDrainState(ptr long)
@ cdecl nvmlDeviceOnSameBoard(ptr ptr ptr)
@ cdecl nvmlDeviceQueryDrainState(ptr ptr)
@ cdecl nvmlDeviceRegisterEvents(ptr int64 ptr)
@ cdecl nvmlDeviceRemoveGpu(ptr)
@ cdecl nvmlDeviceRemoveGpu_v2(ptr long long)
@ cdecl nvmlDeviceResetApplicationsClocks(ptr)
@ cdecl nvmlDeviceResetGpuLockedClocks(ptr)
@ cdecl nvmlDeviceResetMemoryLockedClocks(ptr)
@ cdecl nvmlDeviceResetNvLinkErrorCounters(ptr long)
@ cdecl nvmlDeviceResetNvLinkUtilizationCounter(ptr long long)
@ cdecl nvmlDeviceSetAPIRestriction(ptr long long)
@ cdecl nvmlDeviceSetAccountingMode(ptr long)
@ cdecl nvmlDeviceSetApplicationsClocks(ptr long long)
@ cdecl nvmlDeviceSetAutoBoostedClocksEnabled(ptr long)
@ cdecl nvmlDeviceSetComputeMode(ptr long)
@ cdecl nvmlDeviceSetCpuAffinity(ptr)
@ cdecl nvmlDeviceSetDefaultAutoBoostedClocksEnabled(ptr long long)
@ cdecl nvmlDeviceSetDriverModel(ptr long long)
@ cdecl nvmlDeviceSetEccMode(ptr long)
@ cdecl nvmlDeviceSetGpuLockedClocks(ptr long long)
@ cdecl nvmlDeviceSetGpuOperationMode(ptr long)
@ cdecl nvmlDeviceSetMemoryLockedClocks(ptr long long)
@ cdecl nvmlDeviceSetMigMode(ptr long ptr)
@ cdecl nvmlDeviceSetNvLinkUtilizationControl(ptr long long ptr long)
@ cdecl nvmlDeviceSetPersistenceMode(ptr long)
@ cdecl nvmlDeviceSetPowerManagementLimit(ptr long)
@ cdecl nvmlDeviceSetTemperatureThreshold(ptr long ptr)
@ cdecl nvmlDeviceSetVirtualizationMode(ptr long)
@ cdecl nvmlDeviceValidateInforom(ptr)
@ cdecl nvmlErrorString(long)
@ cdecl nvmlEventSetCreate(ptr)
@ cdecl nvmlEventSetFree(ptr)
@ cdecl nvmlEventSetWait(ptr long long)
@ cdecl nvmlEventSetWait_v2(ptr ptr long)
@ cdecl nvmlGetBlacklistDeviceCount(ptr)
@ cdecl nvmlGetBlacklistDeviceInfoByIndex(long ptr)
@ cdecl nvmlGetExcludedDeviceCount(ptr)
@ cdecl nvmlGetExcludedDeviceInfoByIndex(long ptr)
@ cdecl nvmlGetVgpuCompatibility(ptr ptr ptr)
@ cdecl nvmlGetVgpuVersion(ptr ptr)
@ cdecl nvmlGpuInstanceCreateComputeInstance(ptr long ptr)
@ cdecl nvmlGpuInstanceDestroy(ptr)
@ cdecl nvmlGpuInstanceGetComputeInstanceById(ptr long ptr)
@ cdecl nvmlGpuInstanceGetComputeInstanceProfileInfo(ptr long long ptr)
@ cdecl nvmlGpuInstanceGetComputeInstanceRemainingCapacity(ptr long ptr)
@ cdecl nvmlGpuInstanceGetComputeInstances(ptr long ptr ptr)
@ cdecl nvmlGpuInstanceGetInfo(ptr ptr)
@ cdecl nvmlInit()
@ cdecl nvmlInitWithFlags(long)
@ cdecl nvmlInit_v2()
@ cdecl nvmlInternalGetExportTable(ptr ptr)
@ cdecl nvmlSetVgpuVersion(ptr)
@ cdecl nvmlShutdown()
@ cdecl nvmlSystemGetCudaDriverVersion(ptr)
@ cdecl nvmlSystemGetCudaDriverVersion_v2(ptr)
@ cdecl nvmlSystemGetDriverVersion(ptr long)
@ cdecl nvmlSystemGetHicVersion(ptr ptr)
@ cdecl nvmlSystemGetNVMLVersion(ptr long)
@ cdecl nvmlSystemGetProcessName(long ptr long)
@ cdecl nvmlSystemGetTopologyGpuSet(long ptr ptr)
@ cdecl nvmlUnitGetCount(ptr)
@ cdecl nvmlUnitGetDevices(ptr ptr ptr)
@ cdecl nvmlUnitGetFanSpeedInfo(ptr ptr)
@ cdecl nvmlUnitGetHandleByIndex(long ptr)
@ cdecl nvmlUnitGetLedState(ptr ptr)
@ cdecl nvmlUnitGetPsuInfo(ptr ptr)
@ cdecl nvmlUnitGetTemperature(ptr long ptr)
@ cdecl nvmlUnitGetUnitInfo(ptr ptr)
@ cdecl nvmlUnitSetLedState(ptr ptr)
@ cdecl nvmlVgpuInstanceClearAccountingPids(long)
@ cdecl nvmlVgpuInstanceGetAccountingMode(long ptr)
@ cdecl nvmlVgpuInstanceGetAccountingPids(long ptr ptr)
@ cdecl nvmlVgpuInstanceGetAccountingStats(long long ptr)
@ cdecl nvmlVgpuInstanceGetEccMode(long ptr)
@ cdecl nvmlVgpuInstanceGetEncoderCapacity(long ptr)
@ cdecl nvmlVgpuInstanceGetEncoderSessions(long ptr ptr)
@ cdecl nvmlVgpuInstanceGetEncoderStats(long ptr ptr ptr)
@ cdecl nvmlVgpuInstanceGetFBCSessions(long ptr ptr)
@ cdecl nvmlVgpuInstanceGetFBCStats(long ptr)
@ cdecl nvmlVgpuInstanceGetFbUsage(long ptr)
@ cdecl nvmlVgpuInstanceGetFrameRateLimit(long ptr)
@ cdecl nvmlVgpuInstanceGetGpuInstanceId(long ptr)
@ cdecl nvmlVgpuInstanceGetLicenseStatus(long ptr)
@ cdecl nvmlVgpuInstanceGetMdevUUID(long ptr long)
@ cdecl nvmlVgpuInstanceGetMetadata(long ptr ptr)
@ cdecl nvmlVgpuInstanceGetType(long ptr)
@ cdecl nvmlVgpuInstanceGetUUID(long ptr long)
@ cdecl nvmlVgpuInstanceGetVmDriverVersion(long ptr long)
@ cdecl nvmlVgpuInstanceGetVmID(long ptr long ptr)
@ cdecl nvmlVgpuInstanceSetEncoderCapacity(long long)
@ cdecl nvmlVgpuTypeGetClass(long ptr long)
@ cdecl nvmlVgpuTypeGetDeviceID(long ptr ptr)
@ cdecl nvmlVgpuTypeGetFrameRateLimit(long ptr)
@ cdecl nvmlVgpuTypeGetFramebufferSize(long ptr)
@ cdecl nvmlVgpuTypeGetGpuInstanceProfileId(long ptr)
@ cdecl nvmlVgpuTypeGetLicense(long ptr long)
@ cdecl nvmlVgpuTypeGetMaxInstances(ptr long ptr)
@ cdecl nvmlVgpuTypeGetMaxInstancesPerVm(long ptr)
@ cdecl nvmlVgpuTypeGetName(long ptr long)
@ cdecl nvmlVgpuTypeGetNumDisplayHeads(long ptr)
@ cdecl nvmlVgpuTypeGetResolution(long long ptr ptr)